### ISSUE TITLE
The configuration is invalid. Creating the instance for type IDisposable failed. The given type IContainer is not a concrete type. 

### ISSUE THREAD

**Issue by ryletko** [charlessolar/TodoMVC-DDD-CQRS-EventSourcing#25]
I can not get it working because Application project throws the exception. Please help sort this out.

```
[Fatal] <Unhandled> Unhandled exception
2022-01-24T14:51:58.429887154Z System.AggregateException: One or more errors occurred. (The configuration is invalid. Creating the instance for type IDisposable failed. The given type IContainer is not a concrete type. Please use one of the other overloads to register this type. Verification was triggered because Container.Options.EnableAutoVerification was enabled. To prevent the container from being verified on first resolve, set Container.Options.EnableAutoVerification to false.)
2022-01-24T14:51:58.429906836Z  ---> SimpleInjector.ActivationException: The configuration is invalid. Creating the instance for type IDisposable failed. The given type IContainer is not a concrete type. Please use one of the other overloads to register this type. Verification was triggered because Container.Options.EnableAutoVerification was enabled. To prevent the container from being verified on first resolve, set Container.Options.EnableAutoVerification to false.
2022-01-24T14:51:58.429911150Z  ---> System.InvalidOperationException: The configuration is invalid. Creating the instance for type IDisposable failed. The given type IContainer is not a concrete type. Please use one of the other overloads to register this type.
2022-01-24T14:51:58.429914117Z  ---> SimpleInjector.ActivationException: The given type IContainer is not a concrete type. Please use one of the other overloads to register this type.
2022-01-24T14:51:58.429916775Z    at SimpleInjector.Advanced.DefaultConstructorResolutionBehavior.VerifyTypeIsConcrete(Type implementationType)
2022-01-24T14:51:58.429919403Z    at SimpleInjector.Advanced.DefaultConstructorResolutionBehavior.TryGetConstructor(Type implementationType, String& errorMessage)
2022-01-24T14:51:58.429921993Z    at SimpleInjector.ConstructorResolutionBehaviorExtensions.GetConstructor(IConstructorResolutionBehavior behavior, Type implementationType)
2022-01-24T14:51:58.429924582Z    at SimpleInjector.ContainerOptions.SelectConstructor(Type implementatioType)
2022-01-24T14:51:58.429926954Z    at SimpleInjector.Registration.BuildNewExpression()
2022-01-24T14:51:58.429929215Z    at SimpleInjector.Registration.BuildTransientExpression()
2022-01-24T14:51:58.429931505Z    at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonRegistration.GetInterceptedInstanceWithNullCheck()
2022-01-24T14:51:58.429935198Z    at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonRegistration.GetInterceptedInstance()
2022-01-24T14:51:58.429937648Z    at SimpleInjector.Lifestyles.SingletonLifestyle.SingletonRegistration.BuildExpression()
2022-01-24T14:51:58.429940137Z    at SimpleInjector.InstanceProducer.BuildExpressionInternal()
2022-01-24T14:51:58.429942452Z    at SimpleInjector.Internals.LazyEx`1.InitializeAndReturn()
2022-01-24T14:51:58.429944811Z    at SimpleInjector.InstanceProducer.BuildExpression()
2022-01-24T14:51:58.429947142Z    at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
2022-01-24T14:51:58.429949455Z    --- End of inner exception stack trace ---
2022-01-24T14:51:58.429951812Z    at SimpleInjector.InstanceProducer.VerifyExpressionBuilding()
2022-01-24T14:51:58.429954288Z    at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt(InstanceProducer[] producersToVerify)
2022-01-24T14:51:58.429956912Z    at SimpleInjector.Container.VerifyThatAllExpressionsCanBeBuilt()
2022-01-24T14:51:58.429959293Z    at SimpleInjector.Container.VerifyInternal(Boolean suppressLifestyleMismatchVerification)
2022-01-24T14:51:58.429964546Z    at SimpleInjector.Container.Verify(VerificationOption option)
2022-01-24T14:51:58.429967109Z    at SimpleInjector.Container.Verify()
2022-01-24T14:51:58.429969408Z    at SimpleInjector.Container.NotifyAndLock()
2022-01-24T14:51:58.429971701Z    --- End of inner exception stack trace ---
2022-01-24T14:51:58.429973905Z    at SimpleInjector.Container.NotifyAndLock()
2022-01-24T14:51:58.429976128Z    at SimpleInjector.Container.GetInstance(Type serviceType)
2022-01-24T14:51:58.429978430Z    at Aggregates.Internal.Container.Resolve(Type resolve) in C:\projects\aggregates-net\src\Aggregates.NET.SimpleInjector\Internal\Container.cs:line 119
2022-01-24T14:51:58.429981595Z    at Aggregates.Internal.ContainerAdapter.Build(Type typeToBuild) in C:\projects\aggregates-net\src\Aggregates.NET.NServiceBus\Internal\ContainerAdapter.cs:line 70
2022-01-24T14:51:58.429986890Z    at NServiceBus.Pipeline.RegisterStep.CreateBehavior(IBuilder defaultBuilder)
2022-01-24T14:51:58.429989447Z    at NServiceBus.Pipeline`1.<>c__DisplayClass0_0.<.ctor>b__0(RegisterStep r)
2022-01-24T14:51:58.429992072Z    at System.Linq.Enumerable.SelectListIterator`2.ToArray()
2022-01-24T14:51:58.429994319Z    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
2022-01-24T14:51:58.429996797Z    at NServiceBus.Pipeline`1..ctor(IBuilder builder, PipelineModifications pipelineModifications)
2022-01-24T14:51:58.429999151Z    at NServiceBus.PipelineComponent.CreatePipeline[T](IBuilder builder)
2022-01-24T14:51:58.430001424Z    at NServiceBus.SendComponent.CreateMessageOperations(IBuilder builder, PipelineComponent pipelineComponent)
2022-01-24T14:51:58.430003919Z    at NServiceBus.StartableEndpoint.Start()
2022-01-24T14:51:58.430006526Z    at NServiceBus.HostingComponent.Start(IStartableEndpoint startableEndpoint)
2022-01-24T14:51:58.430009043Z    at NServiceBus.ExternallyManagedContainerHost.Start(IBuilder externalBuilder)
2022-01-24T14:51:58.430011437Z    at Aggregates.Bus.Start(IStartableEndpointWithExternallyManagedContainer nsb) in C:\projects\aggregates-net\src\Aggregates.NET.NServiceBus\Bus.cs:line 32
2022-01-24T14:51:58.430014115Z    at Aggregates.Configuration.Start() in C:\projects\aggregates-net\src\Aggregates.NET\Configure.cs:line 48
2022-01-24T14:51:58.430016574Z    at Example.Program.InitBus() in /src/Application/Endpoint.cs:line 104
2022-01-24T14:51:58.430018990Z    --- End of inner exception stack trace ---
2022-01-24T14:51:58.430021192Z    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
2022-01-24T14:51:58.430023644Z    at System.Threading.Tasks.Task`1.get_Result()
2022-01-24T14:51:58.430025948Z    at Example.Program.Main(String[] args) in /src/Application/Endpoint.cs:line 61
```

**Comment by charlessolar** [comment]
Thanks @ryletko I'll look into this!

Seems like you can fix it for now by doing what the exception says and setting `Container.Options.EnableAutoVerification = false`

Ill go through and update packages soon

**Comment by charlessolar** [comment]
Hi @ryletko just updating you that I am working on the issue and pretty sure I identified the issue. NSB registers things that SimpleInjector doesn't like. Went and looked at NSB's simpleinjector project and found out they set

`container.Options.EnableAutoVerification = false;`

which you can do here https://github.com/charlessolar/TodoMVC-DDD-CQRS-EventSourcing/blob/beb9a3bd11906d9ebdef8a4bca38cbec135b7663/src/Application/Endpoint.cs#L58

to **hopefully** fix this issue temporarily.

In related news I am working on updating Agg.net and all samples to use Microsoft's DI and Logging (see https://github.com/charlessolar/Aggregates.NET/issues/54) which will take more time so this solution should work for now!

**Comment by charlessolar** [comment]
Project has been updated and works again!
